Repository canonical/anbox-cloud.io, pull requests merged in 2020-03, with the labels that each got.

#89 Hide keyboard controls on mobile
  static/js/detect-device.js
  templates/demo.html
Labels: Project, Review: Code +1, Review: QA +1

#90 Small/mobile screens
  static/sass/_pattern_stream.scss
  templates/demo.html
Labels: Project, Review: Code needed, Review: QA needed

#94 Update phone label to mobile/cell
  templates/_engage-form.html
Labels: Review: Code +1, Review: QA +1
