Repository canonical/anbox-cloud.io, pull requests merged in 2020-02, with the labels that each got.

#48 Add Anbox Cloud streaming SDK
  static/js/anbox-stream-docs.md
  static/js/anbox-stream-sdk.js
Labels: Project, Review: Code needed, Review: QA needed

#50 Test add-streaming-sdk
  .gitignore
  requirements.txt
  static/js/anbox-stream-docs.md
  static/js/modules/global-nav/global-nav.js
  templates/demo.html
  tests/test_api.py
  tests/test_routes.py
  webapp/app.py
Labels: Project, Review: Code +1, Review: QA +1

#63 Update invite code info
  README.md
Labels: Project, Review: Code +1

#72 Handle expired tokens
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#74 templates: limit framerate to 25
  templates/demo.html
Labels: Review: Code +1, Review: QA +1

#73 Play button to start instance
  static/sass/_pattern_stream.scss
  static/sass/styles.scss
  templates/_anbox-embed.html
  templates/demo.html
Labels: Project, Review: Code +1, Review: Design +1, Review: QA +1

#75 Update demo URL
  README.md
Labels: Project, Review: Code +1

#76 Handle expired tokens with error codes
  templates/demo.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#79 streaming: go fullscreen when starting a stream on a mobile device
  templates/demo.html
Labels: Project, Review: Code +1, Review: QA +1

#80 Player background
  static/sass/_pattern_stream.scss
  templates/_anbox-embed.html
  templates/demo.html
Labels: Review: Code +1, Review: QA +1

#83 Fix json format to normal string
  templates/401.html
  webapp/app.py
Labels: Project, Review: Code +1, Review: Design +1, Review: QA +1

#84 Add instructions to the stream placeholder
  static/sass/_pattern_stream.scss
  templates/_anbox-embed.html
Labels: Project, Review: Code +1, Review: QA +1

#87 static: hide video media controls in fullscreen mode
  static/sass/_pattern_stream.scss
Labels: Project, Review: Code +1, Review: QA +1

#64 Multistage builds for anbox-cloud
  .dockerignore
  Dockerfile
  requirements.txt
Labels: Review: Code +1, Review: QA +1
