Repository canonical/anbox-cloud.io, pull requests merged in 2021-05, with the labels that each got.

#166 Build anbox-cloud landing page
  package.json
  requirements.txt
  static/sass/_pattern_deployment-table.scss
  static/sass/_pattern_heading-icon.scss
  static/sass/_pattern_navigation.scss
  static/sass/_pattern_strip.scss
  static/sass/_settings.scss
  static/sass/styles.scss
  templates/_engage-form.html
  templates/_layout.html
  templates/contact-us.html
  templates/index.html
  tests/test_routes.py
  webapp/app.py
  yarn.lock
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#174 templates: mention OCI as supported cloud
  templates/index.html
Labels: Review: Code +1

#171 Creates Telco vertical page on Anbox
  static/sass/_pattern_strip.scss
  templates/telco/index.html
  webapp/app.py
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1

#172 Create game-streaming vertical page
  templates/gaming/index.html
  templates/telco/index.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#178 4011 moble app management page build
  templates/enterprise/index.html
  webapp/app.py
Labels: Review: Code +1 (with changes), Review: Design +1, Review: QA +1
