Repository canonical/anbox-cloud.io, pull requests merged in 2024-06, with the labels that each got.

#336 Fix ci pipeline by
  .github/workflows/pr.yaml
Labels: Review: Code +1

#344 [WD-12159] chore: Updated yarn.lock dependencies
  package.json
  yarn.lock
Labels: Review: QA needed

#345 Homepage copy update
  templates/index.html
Labels: Review: Code +1, Review: QA +1
